"""Add cancel_requested_at to Subscription

Revision ID: 13559fef0d92
Revises: 1e5f2197fc76
Create Date: 2026-01-21 00:59:15.140876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13559fef0d92'
down_revision: Union[str, Sequence[str], None] = '1e5f2197fc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancel_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cancel_requested_at')
    # ### end Alembic commands ###
