"""Add stripe identifiers and metadata

Revision ID: 8438d791efa6
Revises: c54084c35b28
Create Date: 2026-01-21 12:30:18.317043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8438d791efa6'
down_revision: Union[str, Sequence[str], None] = 'c54084c35b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('last_payment_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_subscriptions_stripe_price_id'), 'subscriptions', ['stripe_price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_price_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'last_payment_status')
    op.drop_column('subscriptions', 'stripe_price_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###
