"""Add fallback_number to AgentSettings

Revision ID: b48741909d28
Revises: 88d0030593f3
Create Date: 2026-01-25 22:19:09.818724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48741909d28'
down_revision: Union[str, Sequence[str], None] = '88d0030593f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_settings', sa.Column('fallback_number', sa.String(), nullable=True))
    op.alter_column('phone_numbers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=1)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=1)
    op.alter_column('phone_numbers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('agent_settings', 'fallback_number')
    # ### end Alembic commands ###
