"""Replace last_notified_at with notified_at

Revision ID: c54084c35b28
Revises: bf6c473695ec
Create Date: 2026-01-21 03:07:55.692077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54084c35b28'
down_revision: Union[str, Sequence[str], None] = 'bf6c473695ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('notified_at', sa.DateTime(), nullable=True))
    op.drop_column('phone_numbers', 'last_notified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('last_notified_at', sa.DATETIME(), nullable=True))
    op.drop_column('phone_numbers', 'notified_at')
    # ### end Alembic commands ###
